"""updated the product models

Revision ID: 454556b66412
Revises: b17aea589f64
Create Date: 2025-07-21 14:13:28.356914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '454556b66412'
down_revision: Union[str, None] = 'b17aea589f64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blacklisted_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('categories', sa.Column('image', sa.String(), nullable=True))
    op.drop_column('categories', 'image_url')
    op.alter_column('products', 'images',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('products', 'product_type')
    op.drop_column('services', 'device_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('device_type', postgresql.ENUM('UPPER_LIMB', 'LOWER_LIMB', 'HOSPITAL_EQUIPMENT', 'GENERAL', name='devicetype'), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('product_type', postgresql.ENUM('HOSPITAL_EQUIPMENT', 'UPPER_LIMB_DEVICE', 'LOWER_LIMB_DEVICE', 'ACCESSORY', 'CONSUMABLE', name='producttype'), autoincrement=False, nullable=False))
    op.alter_column('products', 'images',
               existing_type=sa.String(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('categories', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('categories', 'image')
    op.alter_column('blacklisted_tokens', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
